### ISSUE TITLE
The list of Dataverse collections is not correctly retrieved (400 error)

### ISSUE THREAD

**Issue by tjouneau** [libis/rdm-integration#1]
Hi,
I'm working into https://bac-dataverse.univ-lorraine.fr (this is a test/sandbox instance).
I have successfully launched the arm64 darwin binary (I'm on a Mac) with the following command :
`./demo_darwin_arm64.bin -dvID=univ-lorraine -server=https://bac-dataverse.univ-lorraine.fr -servername=Bac_UL`
I entered the API token, and clicked on the drop-down menu which is supposed to contain the available collections.
I get the following message : 
```
doi lookup failed: 500 - listing Dataverse objects failed: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```
What do I do wrong?
Thanks in advance,
Thomas

**Comment by ErykKul** [comment]
Hi,

I have just made a new release (v1.1.4) that should contain the fixes helping your problem. Most notably, the timeout problems are addressed there. One of the issues was that when a user is an admin or curator with access to many datasets, the dropdowns could encounter timeouts. This is addressed by retrieving only a subset of them, where you can use the search function for retrieving more specific datasets (e.g., by searching with a word from the title of the dataset).

I hope this solves the problems you encountered. If not, please reopen the issue.

Greetings,
Eryk
